
    <nav >
        <?php if(isset($_SESSION["activeUserID"]) && ($_SESSION["activeUserID"] == 0)) {
            print "<ul class='signup' >";
            print "<li ><a href = 'index.php?page=signup' > Sign Up </a ></li >";
        print "</ul >";
        }
        if(isset($_SESSION["activeUserID"]) && ($_SESSION["activeUserID"] == 0)) {
        print "<ul class='login'>";
            print "<li><a href='index.php?page=login'>Login</a></li>";
        print "</ul>";
        }