<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Responsive design a little bit between these-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Responsive design a little bit between these -->
    <meta name="keywords" content="shpo heroes">
    <meta name="description" content="Shop Heroes HomePage">
    <!--Styles including the icons-->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="stylesheet" type="text/css" href="styleSH.css">
    <link rel="icon" size="192x192" href="images/android.png">
    <title>Welcome to Shop Heroes</title>
</head>

<body>
<header>
    <p class="head"> Welcome to Shop Heroes! Please sign in to get started.</p>
    <!--Search bar to be coded-->
    <form action="index.php?page=searchmehere" method="post"> 
        <table class="search">
            <tr>
                <td>
                    <input type="text" name="terms" size="25" maxlength="25" placeholder="What are you looking for?" class="Searchbar">
                    <input type="submit" value="Search" class="centercell">
                </td>
            </tr>

        </table>
    </form>
    <img src="images/logo.png" width="120" height="100" alt="Welcome to Shop Heroes"> <!--Should NOT be in a div of its own should be in the search div!!!!! -->
    <!--Navigation Bar ...-->
    <nav class="ContainerNav">
        <ul>
            <li><a href="index.php?page=home">Home</a></li>
            <li><a href="index.php?page=aboutus">About Us</a></li>
            <li><a href="index.php?page=order">Orders</a></li>
            <li><a href="index.php?page=myaccount">My Account</a></li>
            <li><a href="index.php?page=contact">Contact us</a></li>
        </ul>
    </nav>
    <nav class="ContainerLogin">
        <?php if(!(isset($_SESSION["activeUser"]))) {
            print "<ul class='signup' >";
            print "<li ><a href = 'index.php?page=signup' > Sign Up </a ></li >";
        print "</ul >";
        }
        if(!(isset($_SESSION["activeUser"]))) {
        print "<ul class='login'>";
            print "<li><a href='index.php?page=login'>Login</a></li>";
        print "</ul>";
        }
//        if(isset($_SESSION["activeUserID"]) && ($_SESSION["activeUserID"] != 0))
//        {
//            print "<ul class='signup'>";
//            print "<li><a href='index.php?page=updateUserInfo'>Update Account</a></li>";
//            print  "</ul>";
//        }
        if(isset($_SESSION["activeUserID"]) && ($_SESSION["activeUserID"] != 0))
        {
         print "<ul class='login'>";
         print "<li><a href='index.php?page=logout'>Logout</a></li>";
         print  "</ul>";
        }
        ?>
    </nav>

</header>

