<section>
 
 <style media="screen" type="text/css">

fieldset { 
    display: block;
    margin-left: 200px;
    margin-right: 10px;
    padding-top: 0.35em;
    padding-bottom: 50px;
    padding-left: 0.75em;
    padding-right: 0.75em;
    border: 2px groove (internal value);
	height: 275px;
	width: 300px;
}
 <?php
    $pulledUserID =$_SESSION['activeUserID'];
    $qry = "SELECT * FROM USERS JOIN CUSTOMERS ON USERS.UserID = CUSTOMERS.UserID WHERE USERS.UserID ='$pulledUserID'";
    $stmt = $pdo->query($qry);
    while ($row = $stmt->fetch()) {
        $emailMatch = true;
        $pulledUser= $row['Username'];
        $pulledPass= $row['Password'];
        $pulledUserID = $row['UserID'];
        $pulledCustID = $row['CustID'];
        $pulledCustFirstN = $row['CustFirstN'];
        $pulledCustLastN = $row['CustLastN'];
        $pulledCustAddress = $row['CustAddress'];
        $pulledCustCity = $row['CustCity'];
        $pulledCustZip = $row['CustZip'];
        $pulledCustPhone = $row['CustPhone'];
    }
 ?>
</style>
	
	<table>
		<td>
	
			<fieldset><legend align="center"> Account Summary :</legend>
				<h5> Email Address:&nbsp &nbsp &nbsp &nbsp<?php print $pulledUser;?></h5>
				<h5> Current Password: &nbsp &nbsp &nbsp &nbsp<?php print "";?></h5>
			</fieldset>
	
		</td>
 
		<td>
			<fieldset><legend align="center">Contact Information and Address : </legend>
			
				<h5> First Name: &nbsp &nbsp &nbsp &nbsp <?php print $pulledCustFirstN;?></h5>
				<h5> Last Name: &nbsp &nbsp &nbsp &nbsp <?php print $pulledCustLastN;?></h5>
				<h5> Street Address: &nbsp &nbsp &nbsp &nbsp <?php print $pulledCustAddress;?></h5>
				<h5> City: &nbsp &nbsp &nbsp &nbsp <?php print $pulledCustCity;?></h5>
				<h5> Zip Code: &nbsp &nbsp &nbsp &nbsp <?php print $pulledCustZip;?></h5>
				<h5> Phone Number: &nbsp &nbsp &nbsp &nbsp <?php print $pulledCustPhone;?></h5>
		</td>
	</table>
	<form action='index.php?page=updateUserInfo'>
		<input type="submit" value="Update Account">
	</form>
</section>