<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
	<meta name="keywords" content="Shopping cart">
	<meta name="description" content="Shopping cart page">
	<link rel="stylesheet" type="text/css" href="ShoppingCart.css">
	<title>Shopping Cart page</title>
</head>
<body>
<?php
if((isset($_SESSION['activeUserID'])) && ($_SESSION['activeUserID'] != 0 ))
{
    if(isset($_COOKIE['cart'])) {
        $cookieCart = $_COOKIE['cart'];
        $cookieCart = stripslashes($cookieCart);
        $cart = json_decode($cookieCart, true);
    }

$qry = 'Select * from `PRODUCTS` JOIN `STORES` ON PRODUCTS.StoreID = STORES.StoreID';
////call quuery
$stmt = $pdo -> query( $qry );
echo "<table class='products'>";
$numProductDisplayed = 0;
while($row = $stmt->fetch()) {   //if its in the cart
    foreach ($cart as $pid => $qty) {
        if ($row['ProductID'] == $pid) {
            //new table row per product
            //        var_dump($row['ProductID']);
            echo "<tr style='outline: thin solid'>";
            $productID = $row['ProductID'];
            //product pictures
            echo "<td><img src='images/products/128/_" . $row['ProductUPC'] . ".png' style='width:128px;height:128px;'></td>";
            //product informations
            echo "<td>ProductName: " . $row['ProductName'] . "<br><br>ProductCategory: " . $row['ProductCategory'] . "<br><br>ProductUPC: " . $row['ProductUPC'] . "</td>";
            echo "<td>UnitPrice: $" . $row['UnitPrice'] . "<br><br>Quantity: " . $row['Quantity'] . "<br><br>Store= ";
            if ($row['StoreID'] == 1) {
                echo "Kroger";
            };
            if ($row['StoreID'] == 2) {
                echo 'Meijer';
            };
            echo "</td>";
            //		echo "StoreID: " . $row['StoreID'] . "<br>";
            //		echo "ProductName: " . $row['ProductName'] . "<br>";
            //		echo "ProductUPC: " . $row['ProductUPC'] . "<br>";
            //		echo "UnitPrice: $" . $row['UnitPrice'] . "<br>";
            //		echo "ProductCategory: " . $row['ProductCategory'] . "<br>";
            //		echo "Description: " . $row['Description'] . "<br>";
            //		echo "Quantity: " . $row['Quantity'] . "<br>";
            //		echo "</div></br>";

            echo "<tr>";
            echo "<td>" . $row['ProductName'] . "</td>"; ?>
            <td></td>
            <td width="12%"></td><?php
            echo "<td>Quantity: $qty</td>";
            echo "<td>Price: " . $row['UnitPrice'] . " </td>";
            echo "<td></td>"; ?>
            </tr>
            <!-- Need to use loop to produce more of this row-->
            <tr><?php
                echo "<td><img src='images/products/128/_" . $row['ProductUPC'] . ".png' style='width:128px;height:128px;'></td>";
                echo "<td>" . $row['ProductUPC'] . "</td>"; ?>
                <td></td>
                <td><input type="number" name="quantity" min="0" value="<?php echo $qty; ?>"></td>
                <td>Code to get price<!--Insert code to get item price--></td>
                <td><img src='#' alt='Garbage can to remove item'></td>

            </tr>
            <?php
        }
    }
}
echo "</table>";
    ?>
<h1>Shopping Cart</h1>
<!-- Shopping Cart Form-->
<form action="#" method="post">
	<div class="items">
	<table class="products">
        <?php


        ?>
		<tr>
			<td>product</td>
			<td> </td>
			<td width="12%"></td>
			<td>Quantity:</td>
			<td>Price:</td>
			<td></td>
		</tr>
		<!-- Need to use loop to produce more of this row-->
			<tr>
                echo "<td><img src='images/products/128/_" . $row['ProductUPC'] . ".png' style='width:128px;height:128px;'></td>";
                <td><!--Name of product-->Name of Product:</td>
				<td></td>
				<td><input type="number" name="#Name for php code" min="0"></td>
				<td>Code to get price<!--Insert code to get item price--></td>
				<td><img src='#' alt='Garbage can to remove item'></td>
		
			</tr>
	</table>
	</div>
		<!-- -->
	<table>
		<tr>
			<td></td>
			<td>Summary:</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>Total before tax:</td>
			<td><!--Price --></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>Shipping:</td>
			<td><!--shipping & Handling cost--></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>Tax:</td>
			<td><!--Tax amount--></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>TOTAL:</td>
			<td><!--Price with Tax--></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td colspan ="2"><input type="Submit" value="Checkout"></td>
			<td><!--Price with Tax--></td>
			<td colspan="3"></td>
		</tr>

		<tr>
			<td></td>
			<td></td>
			<td><!--Price with Tax--></td>
			<td colspan="3"></td>
		</tr>
	</table>
</form>
</body>
<?php }
else{
    array_push($_SESSION['messages'], "You must be logged-in to view 'ShoppingCart'");
    $_SESSION['announcements'] = -1;
    header('Location: index.php?page=login');
    echo "</body>";
}?>

