<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="keywords" content="Shopping cart">
	<meta name="description" content="Shopping cart page">
	<link rel="stylesheet" type="text/css" href="ShoppingCart.css">
	<title>Shopping Cart page</title>
</head>
<body>
<h1>Shopping Cart</h1>
<!-- Shopping Cart Form-->
<form action="#" method="post">
	<div class="items">
	<table>
		<tr>
			<td>product</td>
			<td> </td>
			<td width="12%"></td>
			<td>Quantity:</td>
			<td>Price:</td>
			<td></td>
		</tr>
		<!-- Need to use loop to produce more of this row-->
			<tr>
				<td><img src='#' alt='Picture of product'></td>
				<td><!--Name of product-->Name of Product:</td>
				<td></td>
				<td><input type="number" name="#Name for php code" min="0"></td>
				<td>Code to get price<!--Insert code to get item price--></td>
				<td><img src='#' alt='Garbage can to remove item'></td>
		
			</tr>
	</table>
	</div>
		<!-- -->
	<table>
		<tr>
			<td></td>
			<td>Summary:</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td>Total before tax:</td>
			<td><!--Price --></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>Shipping:</td>
			<td><!--shipping & Handling cost--></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>Tax:</td>
			<td><!--Tax amount--></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td>TOTAL:</td>
			<td><!--Price with Tax--></td>
			<td colspan="3"></td>
		</tr>
		<tr>
			<td></td>
			<td colspan ="2"><input type="Submit" value="Checkout"></td>
			<td><!--Price with Tax--></td>
			<td colspan="3"></td>
		</tr>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td><!--Price with Tax--></td>
			<td colspan="3"></td>
		</tr>
	</table>
</form>
</body>
</html>